"project_id": "872876"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
files: [
  {
    "source": "romfs/javelin/i18n/en.json",
    "translation": "romfs/javelin/i18n/%two_letters_code%.json",
  }
]
